### PR TITLE
Readme 0.1 version for the forkable Event Wallet

### PR DESCRIPTION
**Pull request by Pabl0cks**
This is a first version proposal, to start working from it until we ship it. We'll need to add: 
- Screenshots to replace placeholders when there is a final version of the forkable Event Wallet.
- Tweaks on current features if we change them.
- New features (if we add them).

### CODE REVIEW

**Comment by carletex** [comment]
This is great  @Pabl0cks thanks!!

Pushed some lil tweaks.

I think we can merge this if we add the screenshots, We will be iterating later when we add/change the current features.

**Comment by damianmarti** [comment]
@Pabl0cks The new readme looks great!! Thanks!

**Comment by Pabl0cks** [comment]
Thank you @carletex and @damianmarti. I've just uploaded screenshots for readme 0.1

For the 1.0 version maybe I should add some kind of border to the screenshots, what do you think?

**Comment by carletex** [comment]
Great job @Pabl0cks merging this!

> For the 1.0 version maybe I should add some kind of border to the screenshots, what do you think?

Yep! I think they'll look better (instead of floating around :P)

**Pull request merged**
